[package]
name = "util"
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
circular-buffer = { version = "1.2.0", default-features = false, features = ["embedded-io"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
embassy-boot = { version = "0.7.0" }
embedded-storage-async = "0.4.1"

midi = { path = "../midi", optional = true }

[features]
flash-erase-zero = ["embassy-boot/flash-erase-zero"]
midi = ["dep:midi"]
