[package]
name = "anglo-keyboard"
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
defmt = { version = "1.0.1", optional = true }
defmt-rtt = { version = "1.0.0", optional = true }
panic-probe = { version = "1.0.0", optional = true }
panic-reset = "0.1.1"

assign-resources = "0.5.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-boot = { git = "https://github.com/embassy-rs/embassy.git", features = ["flash-erase-zero"] }
embassy-boot-stm32 = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", features = ["arch-cortex-m", "executor-thread"] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", features = ["stm32l072cb", "time-driver-any"] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", features = ["tick-hz-32_768"] }
portable-atomic = { version = "1.11.1", features = ["unsafe-assume-single-core"] }

i2c-proto = { path = "../lib/i2c-proto" }
util = { path = "../lib/util" }
version = { path = "../lib/version" }

[build-dependencies]
version = { path = "../lib/version" }

[features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "panic-probe/print-defmt",
    "embassy-executor/defmt",
    "embassy-stm32/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "version/defmt",
]

[profile.release]
debug = 2
opt-level = "z"
lto = true
codegen-units = 1
