MEMORY
{
    BOOTLOADER       : ORIGIN = 0x08000000, LENGTH = 8K
    BOOTLOADER_STATE : ORIGIN = 0x08002000, LENGTH = 0x2C00
    FLASH            : ORIGIN = 0x08004C00, LENGTH = 0x15980
    DFU              : ORIGIN = 0x0801A600, LENGTH = 0x15A00

    RAM              : ORIGIN = 0x20000000, LENGTH = 20K
}

__bootloader_state_start = ORIGIN(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);
__bootloader_state_end = ORIGIN(BOOTLOADER_STATE) + LENGTH(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);

__bootloader_dfu_start = ORIGIN(DFU) - ORIGIN(BOOTLOADER);
__bootloader_dfu_end = ORIGIN(DFU) + LENGTH(DFU) - ORIGIN(BOOTLOADER);
