[package]
name = "anglo-controller-bootloader"
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-boot = { git = "https://github.com/embassy-rs/embassy.git", features = ["flash-erase-zero"] }
embassy-boot-stm32 = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", features = ["stm32l072cz"] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git" }
embedded-storage = "0.3.1"
panic-reset = "0.1.1"

[profile.release]
debug = 2
opt-level = "z"
lto = true
