MEMORY
{
    BOOTLOADER       : ORIGIN = 0x08000000, LENGTH = 16K
    BOOTLOADER_STATE : ORIGIN = 0x08004000, LENGTH = 4K
    FLASH            : ORIGIN = 0x08005000, LENGTH = 52K
    DFU              : ORIGIN = 0x08012000, LENGTH = 56K

    RAM              : ORIGIN = 0x20000000, LENGTH = 20K
}

__bootloader_state_start = ORIGIN(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);
__bootloader_state_end = ORIGIN(BOOTLOADER_STATE) + LENGTH(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);

__bootloader_dfu_start = ORIGIN(DFU) - ORIGIN(BOOTLOADER);
__bootloader_dfu_end = ORIGIN(DFU) + LENGTH(DFU) - ORIGIN(BOOTLOADER);
