[package]
name = "midi-concertina-controller"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

circular-buffer = { version = "1.2.0", default-features = false, features = ["embedded-io"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-boot = { version = "0.6.1", features = ["flash-erase-zero"] }
embassy-boot-stm32 = "0.6.0"
embassy-embedded-hal = "0.5.0"
embassy-executor = { version = "0.9.1", features = ["defmt", "arch-cortex-m", "executor-thread"] }
embassy-futures = "0.1.2"
embassy-stm32 = { version = "0.4.0", features = ["defmt", "stm32l072cb", "time-driver-any"] }
embassy-sync = "0.7.2"
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb = { version = "0.5.1", features = ["defmt"] }
embedded-storage-async = "0.4.1"
portable-atomic = { version = "1.11.1", features = ["unsafe-assume-single-core"] }
static_cell = "2.1.1"

midi-tools = { version = "0.1.0", path = "../midi-tools" }

[profile.release]
debug = 2
opt-level = "z"
lto = true
