MEMORY
{
    BOOTLOADER       : ORIGIN = 0x08000000, LENGTH = 16K
    BOOTLOADER_STATE : ORIGIN = 0x08004000, LENGTH = 0x1A00  /* ((4 * ACTIVE_PAGES) + 2) * WRITE_SIZE */
    FLASH            : ORIGIN = 0x08006000, LENGTH = 0xCF80  /* TODO: Bigger */
    DFU              : ORIGIN = 0x08013000, LENGTH = 0xD000

    RAM              : ORIGIN = 0x20000000, LENGTH = 20K
}

__bootloader_state_start = ORIGIN(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);
__bootloader_state_end = ORIGIN(BOOTLOADER_STATE) + LENGTH(BOOTLOADER_STATE) - ORIGIN(BOOTLOADER);

__bootloader_dfu_start = ORIGIN(DFU) - ORIGIN(BOOTLOADER);
__bootloader_dfu_end = ORIGIN(DFU) + LENGTH(DFU) - ORIGIN(BOOTLOADER);
