build: bootloader firmware

provision:
    rustup update
    rustup target add thumbv6m-none-eabi
    rustup component add clippy
    rustup component add rustfmt
    rustup component add llvm-tools
    cargo install cargo-binutils
    cargo install --locked probe-rs-tools

test:
    cd bin2syx && cargo test -r
    cd lib/i2c-proto && cargo test -r
    cd lib/midi && cargo test -r
    cd lib/version && cargo test -r

lint:
    cd bin2syx && cargo clippy --all-targets --all-features -- -D warnings
    cd anglo-bootloader && cargo clippy --all-features -- -D warnings
    cd anglo-keyboard && cargo clippy --all-features -- -D warnings
    cd anglo-controller && cargo clippy --all-features -- -D warnings
    cd lib/i2c-proto && cargo clippy --all-targets --all-features -- -D warnings
    cd lib/midi && cargo clippy --all-targets --all-features -- -D warnings
    cd lib/util && cargo clippy --all-targets --all-features -- -D warnings
    cd lib/version && cargo clippy --all-targets --all-features -- -D warnings

format:
    cd bin2syx && cargo fmt
    cd anglo-bootloader && cargo fmt
    cd anglo-keyboard && cargo fmt
    cd anglo-controller && cargo fmt
    cd lib/i2c-proto && cargo fmt
    cd lib/midi && cargo fmt
    cd lib/util && cargo fmt
    cd lib/version && cargo fmt

clean:
    cd bin2syx && cargo clean
    cd anglo-bootloader && cargo clean
    cd anglo-keyboard && cargo clean
    cd anglo-controller && cargo clean
    cd lib/i2c-proto && cargo clean
    cd lib/midi && cargo clean
    cd lib/util && cargo clean
    cd lib/version && cargo clean
    rm -rf build

[private]
bin2syx:
    cd bin2syx && cargo build -r

[private]
bootloader:
    cd anglo-bootloader && cargo build -r

[private]
keyboard:
    mkdir -p build
    cd anglo-keyboard && cargo objcopy --release -- -O binary ../build/anglo-keyboard.bin

[private]
firmware: bin2syx keyboard
    mkdir -p build
    cd anglo-controller && cargo objcopy --release -- -O binary ../build/anglo-firmware.bin
    ./bin2syx/target/release/bin2syx build/anglo-firmware.bin
