name: Electrical

on:
  push:
    tags: [ "electrical/v[0-9]+.[0-9]+.[0-9]+" ]
    paths: [ "electrical/**", ".github/workflows/electrical.yml" ]
    branches: [ "main" ]
  pull_request:
    paths: [ "electrical/**", ".github/workflows/electrical.yml" ]
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  export:
    strategy:
      matrix:
        board:
          - AngloLeftKeyboard
          - AngloRightKeyboard
          - BellowsSensorA
          - Controller

    runs-on: ubuntu-latest

    steps:
      - name: Install Kicad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-10.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad
      - name: Install Fabrication Toolkit
        working-directory: ${{ runner.temp }}
        run: |
          curl -L https://github.com/bennymeg/Fabrication-Toolkit/releases/download/5.3.1/Fabrication-Toolkit-5.3.1.zip > fabrication-toolkit.zip
          unzip fabrication-toolkit.zip -d fabrication-toolkit

      - uses: actions/checkout@v7
      - name: Export ${{ matrix.board }} Schematic
        working-directory: electrical/${{ matrix.board }}
        run: kicad-cli sch export pdf ${{ matrix.board }}.kicad_sch -o ${{ matrix.board }}-schematic.pdf
      - name: Export ${{ matrix.board }} PCB
        working-directory: electrical/${{ matrix.board }}
        env:
          PYTHONPATH: ${{ runner.temp }}/fabrication-toolkit
        run: |
          python3 -m plugins.cli -t -f -e -nI -nB -p ${{ matrix.board }}.kicad_pcb
          mkdir ${{ matrix.board }}-pcb
          cp production/*.zip ${{ matrix.board }}-pcb/
          cp production/*bom.csv ${{ matrix.board }}-pcb/
          cp production/positions.csv ${{ matrix.board }}-pcb/
          zip -r ${{ matrix.board }}-pcb ${{ matrix.board }}-pcb

      - uses: actions/upload-artifact@v7
        with:
          path: electrical/${{ matrix.board }}/${{ matrix.board }}-schematic.pdf
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          path: electrical/${{ matrix.board }}/${{ matrix.board }}-pcb.zip
          if-no-files-found: error
          archive: false

      - name: Rename Release Artifacts
        if: github.ref_type == 'tag'
        working-directory: electrical/${{ matrix.board }}
        run: |
          mv ${{ matrix.board }}-schematic.pdf ${{ matrix.board }}-schematic-${GITHUB_REF_NAME#electrical/v}.pdf
          mv ${{ matrix.board }}-pcb.zip ${{ matrix.board }}-pcb-${GITHUB_REF_NAME#electrical/v}.zip
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          working_directory: electrical/${{ matrix.board }}
          files: |
            ${{ matrix.board }}-schematic-*.pdf
            ${{ matrix.board }}-pcb-*.zip
