name: Electrical

on:
  push:
    paths: [ "electrical/**", ".github/workflows/electrical.yml" ]
    branches: [ "main" ]
  pull_request:
    paths: [ "electrical/**", ".github/workflows/electrical.yml" ]
    branches: [ "main" ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Install Kicad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-10.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad
      - name: Install Fabrication Toolkit
        working-directory: ${{ runner.temp }}
        run: |
          curl -L https://github.com/bennymeg/Fabrication-Toolkit/releases/download/5.3.1/Fabrication-Toolkit-5.3.1.zip > fabrication-toolkit.zip
          unzip fabrication-toolkit.zip -d fabrication-toolkit
      - uses: actions/checkout@v7
      - name: Export AngloLeftKeyboard
        working-directory: ${{ runner.temp }}/fabrication-toolkit
        run: python3 -m plugins.cli -t -f -e -nI -nB -p ${GITHUB_WORKSPACE}/electrical/AngloLeftKeyboard/AngloLeftKeyboard.kicad_pcb
      - name: Export AngloRightKeyboard
        working-directory: ${{ runner.temp }}/fabrication-toolkit
        run: python3 -m plugins.cli -t -f -e -nI -nB -p ${GITHUB_WORKSPACE}/electrical/AngloRightKeyboard/AngloRightKeyboard.kicad_pcb
      - name: Export BellowsSensorA
        working-directory: ${{ runner.temp }}/fabrication-toolkit
        run: python3 -m plugins.cli -t -f -e -nI -nB -p ${GITHUB_WORKSPACE}/electrical/BellowsSensorA/BellowsSensorA.kicad_pcb
      - name: Export Controller
        working-directory: ${{ runner.temp }}/fabrication-toolkit
        run: python3 -m plugins.cli -t -f -e -nI -nB -p ${GITHUB_WORKSPACE}/electrical/Controller/Controller.kicad_pcb
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-electrical_left-keyboard
          path: |
            electrical/AngloLeftKeyboard/production/*.zip
            electrical/AngloLeftKeyboard/production/*bom.csv
            electrical/AngloLeftKeyboard/production/positions.csv
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-electrical_right-keyboard
          path: |
            electrical/AngloRightKeyboard/production/*.zip
            electrical/AngloRightKeyboard/production/*bom.csv
            electrical/AngloRightKeyboard/production/positions.csv
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-electrical_bellows-sensor-a
          path: |
            electrical/BellowsSensorA/production/*.zip
            electrical/BellowsSensorA/production/*bom.csv
            electrical/BellowsSensorA/production/positions.csv
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-electrical_controller
          path: |
            electrical/Controller/production/*.zip
            electrical/Controller/production/*bom.csv
            electrical/Controller/production/positions.csv
          if-no-files-found: error
