name: Firmware

on:
  push:
    paths: [ "firmware/**", ".github/workflows/firmware.yml" ]
    branches: [ "main" ]
  pull_request:
    paths: [ "firmware/**", ".github/workflows/firmware.yml" ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware

    steps:
      - uses: extractions/setup-just@v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Provision
        run: just provision
      - name: Build
        run: just build
      - name: Test
        run: just test
      - name: Lint
        run: just lint
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-firmware
          path: |
            firmware/anglo-controller-bootloader/target/thumbv6m-none-eabi/release/anglo-controller-bootloader
            firmware/anglo-controller/target/thumbv6m-none-eabi/release/anglo-controller
            firmware/anglo-keyboard-bootloader/target/thumbv6m-none-eabi/release/anglo-keyboard-bootloader
            firmware/anglo-keyboard/target/thumbv6m-none-eabi/release/anglo-keyboard
            firmware/build/anglo-firmware.bin.syx
