name: Mechanical

on:
  push:
    paths: [ "mechanical/**", ".github/workflows/mechanical.yml" ]
    branches: [ "main" ]
  pull_request:
    paths: [ "mechanical/**", ".github/workflows/mechanical.yml" ]
    branches: [ "main" ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Install FreeCAD
        run: |
          sudo snap install freecad
      - uses: actions/checkout@v4
      - name: Export
        working-directory: ./mechanical
        run: freecad.cmd export_all.py
      - uses: actions/upload-artifact@v7
        with:
          name: anglo-mechanical
          path: mechanical/exports/*
          if-no-files-found: error
